extends:
  - pegasus

plugins:
  - angular

overrides:
  - files:
      - '!docs/*'
      - '!src/*'
    extends:
      - pegasus/node
    rules:
      no-console: off

globals:
  angular: true

env:
  browser: true
  jasmine: true
  angular/mocks: true
