extends:
  - airbnb-base

plugins:
  - angular

rules:
  import/no-extraneous-dependencies: off
  no-console: off
  max-len:
    - error
    - code: 120

globals:
  angular: true

env:
  node: true
  browser: true
  jasmine: true
  angular/mocks: true
